-- ============================================================================
-- Kiosko App — Catálogo semilla argentino
--
-- Esto NO es un extra: es requisito de MVP. Nadie carga 400 productos a mano
-- antes de vender el primero. El dueño abre la app, tilda lo que vende, le pone
-- precio y está operativo en diez minutos.
--
-- La tabla es GLOBAL (sin comercio_id) y de lectura pública para autenticados.
-- No trae precios: los precios argentinos duran semanas.
--
-- `popularidad` ordena la lista: lo que más se vende arriba.
-- `alias` es lo que el empleado escribe de verdad en el buscador.
-- ============================================================================

insert into catalogo_base (nombre, marca, presentacion, categoria_sugerida, tipo_venta, alias, popularidad) values

-- ---------------------------------------------------------------- Cigarrillos
('Marlboro Box 20', 'Marlboro', '20 u', 'Cigarrillos', 'UNIDAD', '{marlboro,marl,box}', 100),
('Marlboro Box 10', 'Marlboro', '10 u', 'Cigarrillos', 'UNIDAD', '{marlboro 10,marl 10}', 92),
('Marlboro Gold Box 20', 'Marlboro', '20 u', 'Cigarrillos', 'UNIDAD', '{marlboro gold,gold}', 90),
('Philip Morris Box 20', 'Philip Morris', '20 u', 'Cigarrillos', 'UNIDAD', '{philip,pm,morris}', 95),
('Philip Morris Box 10', 'Philip Morris', '10 u', 'Cigarrillos', 'UNIDAD', '{philip 10,pm 10}', 88),
('Chesterfield Box 20', 'Chesterfield', '20 u', 'Cigarrillos', 'UNIDAD', '{chester,chesterfield}', 85),
('Lucky Strike Box 20', 'Lucky Strike', '20 u', 'Cigarrillos', 'UNIDAD', '{lucky,lucky strike}', 80),
('Camel Box 20', 'Camel', '20 u', 'Cigarrillos', 'UNIDAD', '{camel}', 70),
('Parliament Box 20', 'Parliament', '20 u', 'Cigarrillos', 'UNIDAD', '{parliament,parla}', 68),
('Rothmans Box 20', 'Rothmans', '20 u', 'Cigarrillos', 'UNIDAD', '{rothmans,roth}', 75),
('Rothmans Box 10', 'Rothmans', '10 u', 'Cigarrillos', 'UNIDAD', '{rothmans 10}', 72),
('Viceroy Box 20', 'Viceroy', '20 u', 'Cigarrillos', 'UNIDAD', '{viceroy}', 60),
('Next Box 20', 'Next', '20 u', 'Cigarrillos', 'UNIDAD', '{next}', 58),
('Gitanes Box 20', 'Gitanes', '20 u', 'Cigarrillos', 'UNIDAD', '{gitanes}', 40),
('Encendedor', 'Varios', '1 u', 'Cigarrillos', 'UNIDAD', '{encendedor,chispero,yesquero}', 78),
('Papelillo para armar', 'Varios', '1 u', 'Cigarrillos', 'UNIDAD', '{papelillo,papel,ojo}', 45),
('Tabaco para armar 40 g', 'Varios', '40 g', 'Cigarrillos', 'UNIDAD', '{tabaco,armar}', 50),
('Filtros para armar', 'Varios', '1 u', 'Cigarrillos', 'UNIDAD', '{filtros}', 42),

-- ------------------------------------------------------------------- Gaseosas
('Coca-Cola 500 ml', 'Coca-Cola', '500 ml', 'Bebidas', 'UNIDAD', '{coca,coca 500,cocacola}', 100),
('Coca-Cola 1,5 L', 'Coca-Cola', '1,5 L', 'Bebidas', 'UNIDAD', '{coca 1.5,coca grande}', 96),
('Coca-Cola 2,25 L', 'Coca-Cola', '2,25 L', 'Bebidas', 'UNIDAD', '{coca 2.25,coca familiar}', 90),
('Coca-Cola lata 354 ml', 'Coca-Cola', '354 ml', 'Bebidas', 'UNIDAD', '{coca lata,lata coca}', 94),
('Coca-Cola Zero 500 ml', 'Coca-Cola', '500 ml', 'Bebidas', 'UNIDAD', '{coca zero,zero}', 88),
('Coca-Cola Zero 1,5 L', 'Coca-Cola', '1,5 L', 'Bebidas', 'UNIDAD', '{coca zero 1.5}', 82),
('Sprite 500 ml', 'Sprite', '500 ml', 'Bebidas', 'UNIDAD', '{sprite}', 80),
('Sprite 1,5 L', 'Sprite', '1,5 L', 'Bebidas', 'UNIDAD', '{sprite 1.5}', 74),
('Fanta 500 ml', 'Fanta', '500 ml', 'Bebidas', 'UNIDAD', '{fanta,naranja}', 78),
('Fanta 1,5 L', 'Fanta', '1,5 L', 'Bebidas', 'UNIDAD', '{fanta 1.5}', 70),
('Pepsi 500 ml', 'Pepsi', '500 ml', 'Bebidas', 'UNIDAD', '{pepsi}', 76),
('Pepsi 2,25 L', 'Pepsi', '2,25 L', 'Bebidas', 'UNIDAD', '{pepsi 2.25}', 68),
('Seven Up 500 ml', '7Up', '500 ml', 'Bebidas', 'UNIDAD', '{7up,seven,seven up}', 62),
('Mirinda 500 ml', 'Mirinda', '500 ml', 'Bebidas', 'UNIDAD', '{mirinda}', 55),
('Manaos Cola 2,25 L', 'Manaos', '2,25 L', 'Bebidas', 'UNIDAD', '{manaos,manaos cola}', 84),
('Manaos Naranja 2,25 L', 'Manaos', '2,25 L', 'Bebidas', 'UNIDAD', '{manaos naranja}', 72),
('Secco Pomelo 2,25 L', 'Secco', '2,25 L', 'Bebidas', 'UNIDAD', '{secco,pomelo}', 58),
('Paso de los Toros 1,5 L', 'Paso de los Toros', '1,5 L', 'Bebidas', 'UNIDAD', '{paso,toros,pomelo}', 60),
('Schweppes Tónica 1,5 L', 'Schweppes', '1,5 L', 'Bebidas', 'UNIDAD', '{tonica,schweppes}', 48),

-- ------------------------------------------------------------- Aguas y jugos
('Agua mineral Villavicencio 500 ml', 'Villavicencio', '500 ml', 'Bebidas', 'UNIDAD', '{agua,agua chica,villa}', 92),
('Agua mineral Villa del Sur 1,5 L', 'Villa del Sur', '1,5 L', 'Bebidas', 'UNIDAD', '{agua 1.5,villa del sur}', 86),
('Agua saborizada Levité Pera 1,5 L', 'Levité', '1,5 L', 'Bebidas', 'UNIDAD', '{levite,levite pera}', 80),
('Agua saborizada Levité Naranja 1,5 L', 'Levité', '1,5 L', 'Bebidas', 'UNIDAD', '{levite naranja}', 76),
('Agua saborizada Aquarius Pomelo 1,5 L', 'Aquarius', '1,5 L', 'Bebidas', 'UNIDAD', '{aquarius}', 66),
('Soda sifón 1,5 L', 'Varios', '1,5 L', 'Bebidas', 'UNIDAD', '{soda,sifon}', 64),
('Jugo Baggio Naranja 1 L', 'Baggio', '1 L', 'Bebidas', 'UNIDAD', '{baggio,jugo naranja}', 70),
('Jugo Baggio Multifruta 1 L', 'Baggio', '1 L', 'Bebidas', 'UNIDAD', '{baggio multi}', 62),
('Jugo Cepita Naranja 1 L', 'Cepita', '1 L', 'Bebidas', 'UNIDAD', '{cepita}', 58),
('Jugo en polvo Tang', 'Tang', '18 g', 'Bebidas', 'UNIDAD', '{tang,jugo polvo}', 68),
('Jugo en polvo Clight', 'Clight', '8 g', 'Bebidas', 'UNIDAD', '{clight}', 54),

-- ------------------------------------------------------- Cervezas y alcoholes
('Cerveza Quilmes 1 L', 'Quilmes', '1 L', 'Cervezas', 'UNIDAD', '{quilmes,quilmes litro,birra}', 98),
('Cerveza Quilmes lata 473 ml', 'Quilmes', '473 ml', 'Cervezas', 'UNIDAD', '{quilmes lata,lata}', 92),
('Cerveza Brahma 1 L', 'Brahma', '1 L', 'Cervezas', 'UNIDAD', '{brahma}', 88),
('Cerveza Brahma lata 473 ml', 'Brahma', '473 ml', 'Cervezas', 'UNIDAD', '{brahma lata}', 84),
('Cerveza Stella Artois 975 ml', 'Stella Artois', '975 ml', 'Cervezas', 'UNIDAD', '{stella}', 78),
('Cerveza Andes Origen Roja 473 ml', 'Andes', '473 ml', 'Cervezas', 'UNIDAD', '{andes,andes roja}', 74),
('Cerveza Corona 330 ml', 'Corona', '330 ml', 'Cervezas', 'UNIDAD', '{corona}', 70),
('Cerveza Heineken 473 ml', 'Heineken', '473 ml', 'Cervezas', 'UNIDAD', '{heineken,heine}', 72),
('Cerveza Patagonia Amber Lager 730 ml', 'Patagonia', '730 ml', 'Cervezas', 'UNIDAD', '{patagonia,amber}', 60),
('Cerveza Imperial 1 L', 'Imperial', '1 L', 'Cervezas', 'UNIDAD', '{imperial}', 55),
('Fernet Branca 750 ml', 'Fernet Branca', '750 ml', 'Bebidas', 'UNIDAD', '{fernet,branca}', 86),
('Fernet Branca 450 ml', 'Fernet Branca', '450 ml', 'Bebidas', 'UNIDAD', '{fernet chico}', 74),
('Vino Toro tinto 1 L', 'Toro', '1 L', 'Bebidas', 'UNIDAD', '{toro,vino toro}', 76),
('Vino Termidor tinto 1 L', 'Termidor', '1 L', 'Bebidas', 'UNIDAD', '{termidor}', 68),
('Vino Malbec 750 ml', 'Varios', '750 ml', 'Bebidas', 'UNIDAD', '{malbec,vino}', 64),
('Gancia 950 ml', 'Gancia', '950 ml', 'Bebidas', 'UNIDAD', '{gancia}', 62),
('Vodka Smirnoff 700 ml', 'Smirnoff', '700 ml', 'Bebidas', 'UNIDAD', '{vodka,smirnoff}', 58),
('Aperitivo Cynar 750 ml', 'Cynar', '750 ml', 'Bebidas', 'UNIDAD', '{cynar}', 46),
('Speed Unlimited 250 ml', 'Speed', '250 ml', 'Bebidas', 'UNIDAD', '{speed,energizante}', 80),
('Red Bull 250 ml', 'Red Bull', '250 ml', 'Bebidas', 'UNIDAD', '{red bull,redbull}', 76),
('Monster Energy 473 ml', 'Monster', '473 ml', 'Bebidas', 'UNIDAD', '{monster}', 66),

-- ------------------------------------------------------------------ Alfajores
('Alfajor Jorgito Chocolate', 'Jorgito', '1 u', 'Golosinas', 'UNIDAD', '{jorgito,alfajor jorgito}', 96),
('Alfajor Jorgito Blanco', 'Jorgito', '1 u', 'Golosinas', 'UNIDAD', '{jorgito blanco}', 90),
('Alfajor Guaymallén Chocolate', 'Guaymallén', '1 u', 'Golosinas', 'UNIDAD', '{guaymallen,guayma}', 94),
('Alfajor Guaymallén Blanco', 'Guaymallén', '1 u', 'Golosinas', 'UNIDAD', '{guaymallen blanco}', 88),
('Alfajor Jorgelín', 'Jorgelín', '1 u', 'Golosinas', 'UNIDAD', '{jorgelin}', 78),
('Alfajor Havanna Mixto', 'Havanna', '1 u', 'Golosinas', 'UNIDAD', '{havanna,havana}', 72),
('Alfajor Terrabusi Simple', 'Terrabusi', '1 u', 'Golosinas', 'UNIDAD', '{terrabusi}', 68),
('Alfajor Fantoche Triple', 'Fantoche', '1 u', 'Golosinas', 'UNIDAD', '{fantoche,triple}', 82),
('Alfajor Milka Oreo', 'Milka', '1 u', 'Golosinas', 'UNIDAD', '{milka oreo,milka}', 70),
('Alfajor Block Negro', 'Block', '1 u', 'Golosinas', 'UNIDAD', '{block}', 74),
('Alfajor Tatín', 'Tatín', '1 u', 'Golosinas', 'UNIDAD', '{tatin}', 60),
('Alfajor Suchard', 'Suchard', '1 u', 'Golosinas', 'UNIDAD', '{suchard}', 58),
('Alfajor Capitán del Espacio', 'Capitán del Espacio', '1 u', 'Golosinas', 'UNIDAD', '{capitan}', 52),

-- ------------------------------------------------------------- Chocolates
('Chocolate Milka Leger 55 g', 'Milka', '55 g', 'Golosinas', 'UNIDAD', '{milka,milka leger}', 84),
('Chocolate Cofler Block 100 g', 'Cofler', '100 g', 'Golosinas', 'UNIDAD', '{cofler,cofler block}', 86),
('Chocolate Cofler Aireado 55 g', 'Cofler', '55 g', 'Golosinas', 'UNIDAD', '{cofler aireado,aireado}', 80),
('Chocolate Águila 150 g', 'Águila', '150 g', 'Golosinas', 'UNIDAD', '{aguila,chocolate aguila}', 62),
('Chocolate Shot 35 g', 'Shot', '35 g', 'Golosinas', 'UNIDAD', '{shot}', 78),
('Chocolate Kinder Bueno', 'Kinder', '1 u', 'Golosinas', 'UNIDAD', '{kinder,bueno}', 74),
('Chocolate Bon o Bon', 'Bon o Bon', '1 u', 'Golosinas', 'UNIDAD', '{bon o bon,bombon}', 92),
('Chocolate Bon o Bon caja 8 u', 'Bon o Bon', '8 u', 'Golosinas', 'UNIDAD', '{bon o bon caja}', 66),
('Chocolate Rocklets 40 g', 'Rocklets', '40 g', 'Golosinas', 'UNIDAD', '{rocklets}', 76),
('Chocolate Tita', 'Terrabusi', '1 u', 'Golosinas', 'UNIDAD', '{tita}', 88),
('Chocolate Rhodesia', 'Terrabusi', '1 u', 'Golosinas', 'UNIDAD', '{rhodesia}', 82),
('Chocolate Mantecol 130 g', 'Mantecol', '130 g', 'Golosinas', 'UNIDAD', '{mantecol}', 58),
('Chocolate Bananita Dolca', 'Dolca', '1 u', 'Golosinas', 'UNIDAD', '{bananita,dolca}', 64),
('Chocolate Marroc', 'Marroc', '1 u', 'Golosinas', 'UNIDAD', '{marroc}', 70),
('Huevo Kinder Sorpresa', 'Kinder', '1 u', 'Golosinas', 'UNIDAD', '{kinder sorpresa,huevo}', 60),

-- ---------------------------------------------------- Caramelos y chicles
('Chicle Beldent Menta', 'Beldent', '1 u', 'Golosinas', 'UNIDAD', '{beldent,chicle}', 90),
('Chicle Beldent Frutilla', 'Beldent', '1 u', 'Golosinas', 'UNIDAD', '{beldent frutilla}', 78),
('Chicle Topline Menta', 'Topline', '1 u', 'Golosinas', 'UNIDAD', '{topline}', 74),
('Chicle Bazooka', 'Bazooka', '1 u', 'Golosinas', 'UNIDAD', '{bazooka,globo}', 66),
('Caramelos Sugus', 'Sugus', '1 u', 'Golosinas', 'UNIDAD', '{sugus}', 80),
('Caramelos Media Hora', 'Arcor', '1 u', 'Golosinas', 'UNIDAD', '{media hora}', 72),
('Caramelos Butter Toffees', 'Arcor', '1 u', 'Golosinas', 'UNIDAD', '{butter,toffees}', 76),
('Caramelos Menthoplus', 'Menthoplus', '1 u', 'Golosinas', 'UNIDAD', '{mentho,menthoplus}', 84),
('Pastillas Halls Mentol', 'Halls', '1 u', 'Golosinas', 'UNIDAD', '{halls}', 82),
('Pastillas Tic Tac', 'Tic Tac', '1 u', 'Golosinas', 'UNIDAD', '{tic tac,tictac}', 70),
('Gomitas Mogul Aros', 'Mogul', '1 u', 'Golosinas', 'UNIDAD', '{mogul,gomitas}', 78),
('Gomitas Mogul Dientes', 'Mogul', '1 u', 'Golosinas', 'UNIDAD', '{dientes}', 68),
('Chupetín Pico Dulce', 'Arcor', '1 u', 'Golosinas', 'UNIDAD', '{pico dulce,chupetin}', 74),
('Chupetín Mr. Pop', 'Mr. Pop', '1 u', 'Golosinas', 'UNIDAD', '{mr pop}', 62),
('Turrón Arcor', 'Arcor', '1 u', 'Golosinas', 'UNIDAD', '{turron}', 66),
('Flynn Paff', 'Arcor', '1 u', 'Golosinas', 'UNIDAD', '{flynn,paff}', 60),

-- ---------------------------------------------------------------- Galletitas
('Galletitas Oreo 118 g', 'Oreo', '118 g', 'Galletitas', 'UNIDAD', '{oreo}', 88),
('Galletitas Pepitos 118 g', 'Pepitos', '118 g', 'Galletitas', 'UNIDAD', '{pepitos}', 82),
('Galletitas Rumba', 'Terrabusi', '1 u', 'Galletitas', 'UNIDAD', '{rumba}', 74),
('Galletitas Chocolinas 170 g', 'Chocolinas', '170 g', 'Galletitas', 'UNIDAD', '{chocolinas}', 76),
('Galletitas Manon 130 g', 'Manon', '130 g', 'Galletitas', 'UNIDAD', '{manon}', 62),
('Galletitas Melba 130 g', 'Melba', '130 g', 'Galletitas', 'UNIDAD', '{melba}', 58),
('Galletitas Criollitas 100 g', 'Criollitas', '100 g', 'Galletitas', 'UNIDAD', '{criollitas}', 84),
('Galletitas Express 100 g', 'Express', '100 g', 'Galletitas', 'UNIDAD', '{express}', 78),
('Galletitas Traviata 100 g', 'Traviata', '100 g', 'Galletitas', 'UNIDAD', '{traviata}', 80),
('Galletitas Sonrisas 118 g', 'Sonrisas', '118 g', 'Galletitas', 'UNIDAD', '{sonrisas}', 70),
('Galletitas Merengadas', 'Bagley', '1 u', 'Galletitas', 'UNIDAD', '{merengadas}', 64),
('Galletitas Don Satur saladas', 'Don Satur', '200 g', 'Galletitas', 'UNIDAD', '{don satur,bizcochos}', 86),
('Galletitas Don Satur dulces', 'Don Satur', '200 g', 'Galletitas', 'UNIDAD', '{don satur dulce}', 78),
('Galletitas 9 de Oro dulces', '9 de Oro', '200 g', 'Galletitas', 'UNIDAD', '{9 de oro,nueve de oro}', 76),
('Vainillas Canale 150 g', 'Canale', '150 g', 'Galletitas', 'UNIDAD', '{vainillas}', 68),
('Bizcochos de grasa 200 g', 'Varios', '200 g', 'Galletitas', 'UNIDAD', '{bizcochos,grasa}', 72),
('Obleas Bon o Bon', 'Bon o Bon', '1 u', 'Galletitas', 'UNIDAD', '{obleas}', 66),
('Galletitas Ópera 100 g', 'Ópera', '100 g', 'Galletitas', 'UNIDAD', '{opera}', 60),
('Galletitas Diversión', 'Bagley', '1 u', 'Galletitas', 'UNIDAD', '{diversion}', 58),

-- -------------------------------------------------------- Snacks y copetín
('Papas Lays Clásicas 65 g', 'Lays', '65 g', 'Snacks', 'UNIDAD', '{lays,papas,papas fritas}', 90),
('Papas Lays Clásicas 145 g', 'Lays', '145 g', 'Snacks', 'UNIDAD', '{lays grande}', 80),
('Papas Pehuamar 65 g', 'Pehuamar', '65 g', 'Snacks', 'UNIDAD', '{pehuamar}', 74),
('Palitos Pehuamar 65 g', 'Pehuamar', '65 g', 'Snacks', 'UNIDAD', '{palitos}', 78),
('Doritos Queso 77 g', 'Doritos', '77 g', 'Snacks', 'UNIDAD', '{doritos}', 84),
('Chizitos 60 g', 'Chizitos', '60 g', 'Snacks', 'UNIDAD', '{chizitos,chizito}', 82),
('Twistos 60 g', 'Twistos', '60 g', 'Snacks', 'UNIDAD', '{twistos}', 66),
('Maní salado 100 g', 'Varios', '100 g', 'Snacks', 'UNIDAD', '{mani,mani salado}', 76),
('Maní con chocolate 100 g', 'Varios', '100 g', 'Snacks', 'UNIDAD', '{mani chocolate}', 62),
('Palitos salados 100 g', 'Varios', '100 g', 'Snacks', 'UNIDAD', '{palitos salados}', 64),
('Pochoclo dulce', 'Varios', '1 u', 'Snacks', 'UNIDAD', '{pochoclo,pururu}', 58),
('Nachos con queso', 'Varios', '1 u', 'Snacks', 'UNIDAD', '{nachos}', 54),

-- --------------------------------------------------------------- Panadería
('Pan francés', 'Varios', 'kg', 'Panadería', 'PESO', '{pan,pan frances,flauta}', 96),
('Pan de mesa', 'Varios', 'kg', 'Panadería', 'PESO', '{pan de mesa,felipe}', 82),
('Facturas', 'Varios', 'kg', 'Panadería', 'PESO', '{facturas,medialuna}', 88),
('Medialunas', 'Varios', 'kg', 'Panadería', 'PESO', '{medialunas}', 90),
('Pan lactal Bimbo 390 g', 'Bimbo', '390 g', 'Panadería', 'UNIDAD', '{lactal,bimbo,pan lactal}', 86),
('Pan de hamburguesa x4', 'Varios', '4 u', 'Panadería', 'UNIDAD', '{pan hamburguesa}', 72),
('Pan de pancho x4', 'Varios', '4 u', 'Panadería', 'UNIDAD', '{pan pancho,pancho}', 70),
('Tostadas de arroz 100 g', 'Varios', '100 g', 'Panadería', 'UNIDAD', '{tostadas arroz}', 52),

-- ------------------------------------------------------------- Fiambrería
('Jamón cocido', 'Varios', 'kg', 'Fiambrería', 'PESO', '{jamon,jamon cocido}', 94),
('Jamón crudo', 'Varios', 'kg', 'Fiambrería', 'PESO', '{crudo,jamon crudo}', 70),
('Queso cremoso', 'Varios', 'kg', 'Fiambrería', 'PESO', '{queso,cremoso}', 92),
('Queso de máquina', 'Varios', 'kg', 'Fiambrería', 'PESO', '{queso maquina,tybo}', 86),
('Queso port salut', 'Varios', 'kg', 'Fiambrería', 'PESO', '{port salut,portsalut}', 74),
('Salame milán', 'Varios', 'kg', 'Fiambrería', 'PESO', '{salame,salame milan}', 78),
('Salamín', 'Varios', 'kg', 'Fiambrería', 'PESO', '{salamin}', 72),
('Mortadela', 'Varios', 'kg', 'Fiambrería', 'PESO', '{mortadela}', 68),
('Bondiola', 'Varios', 'kg', 'Fiambrería', 'PESO', '{bondiola}', 60),
('Panceta ahumada', 'Varios', 'kg', 'Fiambrería', 'PESO', '{panceta}', 62),
('Queso rallado 80 g', 'Varios', '80 g', 'Fiambrería', 'UNIDAD', '{rallado,queso rallado}', 64),

-- ------------------------------------------------------------------ Lácteos
('Leche entera sachet 1 L', 'La Serenísima', '1 L', 'Lácteos', 'UNIDAD', '{leche,sachet,leche entera}', 96),
('Leche descremada sachet 1 L', 'La Serenísima', '1 L', 'Lácteos', 'UNIDAD', '{leche descremada}', 84),
('Leche larga vida 1 L', 'La Serenísima', '1 L', 'Lácteos', 'UNIDAD', '{larga vida,leche caja}', 78),
('Leche chocolatada Cindor 1 L', 'Cindor', '1 L', 'Lácteos', 'UNIDAD', '{cindor,chocolatada}', 82),
('Yogur bebible Ser 1 L', 'Ser', '1 L', 'Lácteos', 'UNIDAD', '{yogur,ser}', 74),
('Yogur firme Sancor 190 g', 'Sancor', '190 g', 'Lácteos', 'UNIDAD', '{yogur firme}', 66),
('Manteca 200 g', 'La Serenísima', '200 g', 'Lácteos', 'UNIDAD', '{manteca}', 76),
('Crema de leche 200 ml', 'La Serenísima', '200 ml', 'Lácteos', 'UNIDAD', '{crema}', 62),
('Dulce de leche 400 g', 'La Serenísima', '400 g', 'Lácteos', 'UNIDAD', '{dulce de leche,ddl}', 80),
('Queso untable 190 g', 'Casancrem', '190 g', 'Lácteos', 'UNIDAD', '{casancrem,untable}', 68),
('Huevos x6', 'Varios', '6 u', 'Lácteos', 'UNIDAD', '{huevos,huevos 6}', 88),
('Huevos x12', 'Varios', '12 u', 'Lácteos', 'UNIDAD', '{huevos 12,maple}', 84),
('Postre Danette', 'Danette', '1 u', 'Lácteos', 'UNIDAD', '{danette,postre}', 58),
('Flan Ser', 'Ser', '1 u', 'Lácteos', 'UNIDAD', '{flan}', 54),

-- ------------------------------------------------------------------ Helados
('Helado palito Bombón Suizo', 'Frigor', '1 u', 'Helados', 'UNIDAD', '{bombon suizo,palito}', 84),
('Helado palito Torpedo', 'Frigor', '1 u', 'Helados', 'UNIDAD', '{torpedo}', 76),
('Helado Cucurucho', 'Frigor', '1 u', 'Helados', 'UNIDAD', '{cucurucho}', 72),
('Helado Almendrado', 'Frigor', '1 u', 'Helados', 'UNIDAD', '{almendrado}', 66),
('Helado pote 1 kg', 'Varios', '1 kg', 'Helados', 'UNIDAD', '{pote,helado kilo}', 62),
('Palito de agua', 'Varios', '1 u', 'Helados', 'UNIDAD', '{palito agua,palito}', 70),

-- ----------------------------------------------------------------- Almacén
('Yerba mate Playadito 1 kg', 'Playadito', '1 kg', 'Almacén', 'UNIDAD', '{playadito,yerba}', 92),
('Yerba mate Taragüi 1 kg', 'Taragüi', '1 kg', 'Almacén', 'UNIDAD', '{taragui,yerba taragui}', 88),
('Yerba mate Rosamonte 1 kg', 'Rosamonte', '1 kg', 'Almacén', 'UNIDAD', '{rosamonte}', 84),
('Yerba mate CBSé 500 g', 'CBSé', '500 g', 'Almacén', 'UNIDAD', '{cbse}', 68),
('Azúcar Ledesma 1 kg', 'Ledesma', '1 kg', 'Almacén', 'UNIDAD', '{azucar,ledesma}', 90),
('Harina 000 1 kg', 'Varios', '1 kg', 'Almacén', 'UNIDAD', '{harina,harina 000}', 82),
('Harina leudante 1 kg', 'Varios', '1 kg', 'Almacén', 'UNIDAD', '{leudante}', 70),
('Aceite Natura 900 ml', 'Natura', '900 ml', 'Almacén', 'UNIDAD', '{aceite,natura}', 86),
('Aceite de girasol 1,5 L', 'Varios', '1,5 L', 'Almacén', 'UNIDAD', '{aceite girasol}', 74),
('Arroz largo fino 1 kg', 'Gallo', '1 kg', 'Almacén', 'UNIDAD', '{arroz}', 84),
('Fideos guiseros 500 g', 'Matarazzo', '500 g', 'Almacén', 'UNIDAD', '{fideos,guiseros}', 86),
('Fideos spaghetti 500 g', 'Matarazzo', '500 g', 'Almacén', 'UNIDAD', '{spaghetti,tallarines}', 80),
('Puré de tomate 520 g', 'Arcor', '520 g', 'Almacén', 'UNIDAD', '{pure de tomate,tomate}', 82),
('Tomate triturado 520 g', 'Varios', '520 g', 'Almacén', 'UNIDAD', '{triturado}', 72),
('Atún al natural 170 g', 'La Campagnola', '170 g', 'Almacén', 'UNIDAD', '{atun}', 76),
('Arvejas en lata 350 g', 'Arcor', '350 g', 'Almacén', 'UNIDAD', '{arvejas}', 68),
('Lentejas 400 g', 'Varios', '400 g', 'Almacén', 'UNIDAD', '{lentejas}', 56),
('Sal fina 500 g', 'Celusal', '500 g', 'Almacén', 'UNIDAD', '{sal}', 74),
('Café La Virginia 100 g', 'La Virginia', '100 g', 'Almacén', 'UNIDAD', '{cafe,la virginia}', 78),
('Café instantáneo Nescafé 100 g', 'Nescafé', '100 g', 'Almacén', 'UNIDAD', '{nescafe}', 72),
('Té en saquitos x25', 'Taragüi', '25 u', 'Almacén', 'UNIDAD', '{te,saquitos}', 66),
('Mate cocido x25', 'Taragüi', '25 u', 'Almacén', 'UNIDAD', '{mate cocido}', 62),
('Mayonesa Hellmanns 237 g', 'Hellmanns', '237 g', 'Almacén', 'UNIDAD', '{mayonesa}', 78),
('Ketchup Hellmanns 237 g', 'Hellmanns', '237 g', 'Almacén', 'UNIDAD', '{ketchup}', 66),
('Mostaza 237 g', 'Hellmanns', '237 g', 'Almacén', 'UNIDAD', '{mostaza}', 58),
('Mermelada de durazno 454 g', 'Arcor', '454 g', 'Almacén', 'UNIDAD', '{mermelada}', 60),
('Miel 500 g', 'Varios', '500 g', 'Almacén', 'UNIDAD', '{miel}', 52),
('Polenta 500 g', 'Presto Pronta', '500 g', 'Almacén', 'UNIDAD', '{polenta}', 58),
('Caldo en cubos x6', 'Knorr', '6 u', 'Almacén', 'UNIDAD', '{caldo,cubitos}', 64),
('Sopa instantánea', 'Knorr', '1 u', 'Almacén', 'UNIDAD', '{sopa}', 56),
('Gelatina en polvo', 'Exquisita', '1 u', 'Almacén', 'UNIDAD', '{gelatina}', 54),
('Flan en polvo', 'Exquisita', '1 u', 'Almacén', 'UNIDAD', '{flan polvo}', 50),
('Vinagre de alcohol 500 ml', 'Varios', '500 ml', 'Almacén', 'UNIDAD', '{vinagre}', 56),
('Pan rallado 500 g', 'Preferido', '500 g', 'Almacén', 'UNIDAD', '{pan rallado,rebozador}', 62),

-- --------------------------------------------------------------- Limpieza
('Lavandina 1 L', 'Ayudín', '1 L', 'Limpieza', 'UNIDAD', '{lavandina,ayudin}', 86),
('Detergente 750 ml', 'Magistral', '750 ml', 'Limpieza', 'UNIDAD', '{detergente,magistral}', 84),
('Jabón en polvo 800 g', 'Ala', '800 g', 'Limpieza', 'UNIDAD', '{jabon en polvo,ala}', 76),
('Jabón blanco en pan', 'Federal', '1 u', 'Limpieza', 'UNIDAD', '{jabon blanco,federal}', 70),
('Suavizante 900 ml', 'Vivere', '900 ml', 'Limpieza', 'UNIDAD', '{suavizante,vivere}', 66),
('Limpiador de pisos 900 ml', 'Procenex', '900 ml', 'Limpieza', 'UNIDAD', '{limpiapisos,procenex}', 68),
('Esponja para vajilla', 'Varios', '1 u', 'Limpieza', 'UNIDAD', '{esponja}', 72),
('Papel higiénico x4', 'Higienol', '4 u', 'Limpieza', 'UNIDAD', '{papel higienico,papel}', 94),
('Papel higiénico x2', 'Higienol', '2 u', 'Limpieza', 'UNIDAD', '{papel 2}', 82),
('Rollo de cocina x2', 'Sussex', '2 u', 'Limpieza', 'UNIDAD', '{rollo cocina}', 74),
('Servilletas x100', 'Varios', '100 u', 'Limpieza', 'UNIDAD', '{servilletas}', 68),
('Bolsas de residuo x10', 'Varios', '10 u', 'Limpieza', 'UNIDAD', '{bolsas,residuo,consorcio}', 78),
('Insecticida en aerosol', 'Raid', '1 u', 'Limpieza', 'UNIDAD', '{raid,insecticida}', 62),
('Fósforos', 'Varios', '1 u', 'Limpieza', 'UNIDAD', '{fosforos}', 58),
('Vela', 'Varios', '1 u', 'Limpieza', 'UNIDAD', '{vela}', 46),

-- ---------------------------------------------------------------- Perfumería
('Shampoo 400 ml', 'Sedal', '400 ml', 'Perfumería', 'UNIDAD', '{shampoo,sedal}', 70),
('Acondicionador 400 ml', 'Sedal', '400 ml', 'Perfumería', 'UNIDAD', '{acondicionador}', 62),
('Jabón de tocador', 'Lux', '1 u', 'Perfumería', 'UNIDAD', '{jabon tocador,lux}', 72),
('Pasta dental 90 g', 'Colgate', '90 g', 'Perfumería', 'UNIDAD', '{colgate,pasta dental,dentifrico}', 78),
('Cepillo de dientes', 'Colgate', '1 u', 'Perfumería', 'UNIDAD', '{cepillo}', 60),
('Desodorante en aerosol 150 ml', 'Rexona', '150 ml', 'Perfumería', 'UNIDAD', '{desodorante,rexona}', 74),
('Toallitas femeninas x8', 'Always', '8 u', 'Perfumería', 'UNIDAD', '{toallitas,always}', 76),
('Protectores diarios x15', 'Always', '15 u', 'Perfumería', 'UNIDAD', '{protectores}', 58),
('Pañales x10', 'Pampers', '10 u', 'Perfumería', 'UNIDAD', '{pañales,pampers}', 66),
('Preservativos x3', 'Prime', '3 u', 'Perfumería', 'UNIDAD', '{preservativos,forros}', 70),
('Maquinita de afeitar x2', 'Gillette', '2 u', 'Perfumería', 'UNIDAD', '{gillette,maquinita}', 62),
('Algodón 100 g', 'Estrella', '100 g', 'Perfumería', 'UNIDAD', '{algodon}', 48),
('Alcohol en gel 250 ml', 'Varios', '250 ml', 'Perfumería', 'UNIDAD', '{alcohol en gel,gel}', 54),
('Curitas x10', 'Curitas', '10 u', 'Perfumería', 'UNIDAD', '{curitas,banditas}', 56),
('Aspirina x10', 'Bayer', '10 u', 'Perfumería', 'UNIDAD', '{aspirina}', 68),
('Ibuprofeno 400 x10', 'Varios', '10 u', 'Perfumería', 'UNIDAD', '{ibuprofeno,ibu}', 72),
('Paracetamol 500 x10', 'Varios', '10 u', 'Perfumería', 'UNIDAD', '{paracetamol}', 66),

-- -------------------------------------------------------------- Librería
('Birome azul', 'Bic', '1 u', 'Librería', 'UNIDAD', '{birome,lapicera,bic}', 74),
('Birome negra', 'Bic', '1 u', 'Librería', 'UNIDAD', '{birome negra}', 70),
('Lápiz negro', 'Faber', '1 u', 'Librería', 'UNIDAD', '{lapiz}', 62),
('Goma de borrar', 'Faber', '1 u', 'Librería', 'UNIDAD', '{goma}', 58),
('Cuaderno 48 hojas', 'Rivadavia', '1 u', 'Librería', 'UNIDAD', '{cuaderno}', 68),
('Repuesto hojas x480', 'Éxito', '480 u', 'Librería', 'UNIDAD', '{repuesto,hojas}', 60),
('Resma A4', 'Varios', '500 u', 'Librería', 'UNIDAD', '{resma}', 46),
('Cinta adhesiva', 'Varios', '1 u', 'Librería', 'UNIDAD', '{cinta,scotch}', 56),
('Pegamento en barra', 'Varios', '1 u', 'Librería', 'UNIDAD', '{plasticola,pegamento}', 52),
('Pilas AA x2', 'Duracell', '2 u', 'Librería', 'UNIDAD', '{pilas,pila aa}', 72),
('Pilas AAA x2', 'Duracell', '2 u', 'Librería', 'UNIDAD', '{pila aaa}', 66),

-- -------------------------------------------------------------- Servicios
('Recarga de celular', 'Varios', '—', 'Servicios', 'UNIDAD', '{recarga,credito,carga}', 90),
('Carga de SUBE', 'SUBE', '—', 'Servicios', 'UNIDAD', '{sube,carga sube}', 94),
('Fotocopia', 'Varios', '1 u', 'Servicios', 'UNIDAD', '{fotocopia,copia}', 76),
('Impresión', 'Varios', '1 u', 'Servicios', 'UNIDAD', '{impresion,imprimir}', 70),
('Hielo 3 kg', 'Varios', '3 kg', 'Servicios', 'UNIDAD', '{hielo}', 74),
('Garrafa 10 kg', 'Varios', '10 kg', 'Servicios', 'UNIDAD', '{garrafa}', 60);

-- Los SERVICIO se importan con tipo_producto = 'SERVICIO' desde la app: mueven
-- el monto total en caja pero el margen es SOLO la comisión. Si no se separan,
-- los reportes de rentabilidad mienten por decenas de miles de pesos.
